//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bsp_ef_wpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nachricht
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nachricht()
        {
            this.NutzerEmpfaenger = new HashSet<Nutzer>();
        }
    
        public int ID_Nachricht { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Zeitstempel { get; set; }
        public Nullable<int> Sender { get; set; }
    
        public virtual Nutzer NutzerSender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nutzer> NutzerEmpfaenger { get; set; }
    }
}
